//todo BLOG
//*crud
export let GET_ALL_POSTS = "GET_ALL_POSTS";
export let GET_POST_BY_ID = "GET_POST_BY_ID";
export let CLEAR_POST_DETAILS = "CLEAR_POST_DETAILS";
export const POST_BLOG = "POST_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";

//*search
export let SEARCH_POSTS = "SEARCH_POSTS";
export let UPDATE_SEARCH = "UPDATE_SEARCH";

//*filters
export let FILTER_POSTS = "FILTER_POSTS";
export let UPDATE_FILTERS = "UPDATE_FILTERS";

//todo CLIENTS
export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENT_DETAIL = "GET_CLIENT_DETAIL";
export const POST_CLIENT = "POST_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const REGISTER = "REGISTER";
export const GET_DELETED_CLIENTS = "GET_DELETED_CLIENTS";
export const RESTORE_CLIENT = "RESTORE_CLIENT";
export const EMPTY_DETAIL = "EMPTY_DETAIL"

//todo TESTIMONIALS, ACTIVITIES and PLANS
export const GET_ALL_TESTIMONIALS = 'GET_ALL_TESTIMONIALS';
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const GET_ALL_PLANS = 'GET_ALL_PLANS';
export const EDIT_PLANS = 'EDIT_PLANS';
export const POST_PLANS = 'POST_PLANS';
export const DELETE_PLAN = 'DELETE_PLAN';
export const GET_ACTUAL_PLAN = "GET_ACTUAL_PLAN";
export const POST_REVIEW = 'POST_REVIEW';
export const POST_ACTIVITIES = 'POST_ACTIVITIES';
export const PUT_TESTIMONIALS = 'PUT_TESTIMONIALS';
export const REVIEW = 'REVIEW';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const DELETE_TESTIMONIALS = "DELETE_TESTIMONIALS";
export const PUT_ACTIVITY = 'PUT_ACTIVITY'
export const EMPTY_ACTIVITY = 'EMPTY_ACTIVITY'
export const FILL_ACTIVITY = 'FILL_ACTIVITY'

//todo Calendario
export const GET_CALENDAR = "GET_CALENDAR";
export const POST_CALENDAR = "POST_CALENDAR";
export const DELETE_CALENDAR = "DELETE_CALENDAR";
export const PUT_CALENDAR = "PUT_CALENDAR";

//todo ADMIN
export const GET_ALL_ADMIN = "GET_ALL_ADMIN";
export const POST_ADMIN = "POST_ADMIN";
export const REMOVE_ADMIN = "REMOVE_ADMIN";

//todo PAYMENTS
export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const POST_PAYMENT = "POST_PAYMENT";
export const POST_PAYMENT_CASH = "POST_PAYMENT_CASH";
export const DELETE_PAYMENT_CASH = "DELETE_PAYMENT_CASH";
export const GET_PAYMENTS_BY_USER = "GET_PAYMENTS_BY_USERS";

//todo TRAINERS
export const GET_TRAINERS = "GET_TRAINERS";
export const POST_TRAINER = "POST_TRAINER";
export const PUT_TRAINER = "PUT_TRAINER";
export const DELETE_TRAINER = "DELETE_TRAINER";
