export let GET_ALL_POSTS = 'GET_ALL_POSTS'
export let GET_POST_BY_ID = 'GET_POST_BY_ID'
export let SEARCH_POSTS = 'SEARCH_POSTS'
export let UPDATE_SEARCH = 'UPDATE_SEARCH'
export const GET_CLIENT_DETAIL = 'GET_CLIENT_DETAIL'; // * PARA TRAER EL CLIENTE POR ID  RENDERIZAR EN CADA PERFIL
export const POST_CLIENT = 'POST_CLIENT'; // * PARA REGISTRO DE CLIENTE
