//todo BLOG
//*get
export let GET_ALL_POSTS = 'GET_ALL_POSTS';
export let GET_POST_BY_ID = 'GET_POST_BY_ID';
export let CLEAR_POST_DETAILS = 'CLEAR_POST_DETAILS';

//*search
export let SEARCH_POSTS = 'SEARCH_POSTS';
export let UPDATE_SEARCH = 'UPDATE_SEARCH';

//*filters
export let FILTER_POSTS = 'FILTER_POSTS';
export let UPDATE_FILTERS = 'UPDATE_FILTERS';

//todo CLIENTS
export const GET_CLIENT_DETAIL = 'GET_CLIENT_DETAIL'; // * PARA TRAER EL CLIENTE POR ID  RENDERIZAR EN CADA PERFIL
export const POST_CLIENT = 'POST_CLIENT'; // * PARA REGISTRO DE CLIENTE

//todo CREATE BLOG
export const POST_BLOG = 'POST_BLOG'
export const GET_CLIENTS = 'GET_CLIENTS';

//todo TESTIMONIALS and ACTIVITIES
export const GET_ALL_TESTIMONIALS = 'GET_ALL_TESTIMONIALS'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'